### PR TITLE
Fix lint on tests (fixes #393)

### LINKED ISSUE #393: Lint tests
Seems tests aren't being lint-checked or the config is wrong.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #393

### CODE REVIEW

File: tasks/eslint.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ module.exports = {
     src: [
       'public/js/**/*.js*',
       '!public/js/bundle.js',
-      'tests/*.*',
+      'tests/**/*.js*',
```
Comment (kumar303) [inline tasks/eslint.js]: d'oh

**Comment by kumar303** [comment]
Nice!

r+ute (unless travis explodes)

File: tasks/eslint.js (hunk 1 above)
Comment (muffinresearch) [inline tasks/eslint.js]: Yeah, I missed this when changing to have tests under specific dirs.
