### PR TITLE
Show an error for invalid products (fixes #99)

### LINKED ISSUE #99: Show user friendly error when product ID is wrong
It's possible that the 3rd party who requests payment for a product will send us the wrong product ID. This could be due to a typo or an out of date configuration. In https://github.com/mozilla/payments-ui/pull/94/ we will throw a JS exception for this but that will result in a spinner. Instead, we should show the user an explanation of what happened. Something like "This product cannot be purchased due to a configuration error."

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/payments-ui/issues/99

screenshot 2015-09-03 17 13 35

### CODE REVIEW

**Comment by kumar303** [comment]
@brampitoyo does this look ok? I couldn't find a UX mock in the docs for this kind of stop-the-world error (I vaguely recall you spec'd this out though). Note that this is different than https://github.com/mozilla/payments-ui/issues/282 because it's for the purchase flow, not the management flow.

File: public/js/apps/transaction/app.jsx [hunk 1]
```diff
@@ -34,55 +35,75 @@ export class TransactionApp extends Component {
 
   constructor(props) {
     super(props);
+    this.boundAppActions = bindActionCreators(appActions, this.props.dispatch);
```
Comment (muffinresearch) [inline public/js/apps/transaction/app.jsx]: Can you use `props` instead of `this.props` here as they're passed?

File: tests/reducers/test.app-reducer.js [hunk 2]
```diff
@@ -10,6 +10,7 @@ describe('App Reducer', function() {
     return {
       error: {
         debugMessage: 'some informative message',
+        userMessage: undefined,
```
Comment (muffinresearch) [inline tests/reducers/test.app-reducer.js]: Is this for readability? Otherwise the unset key will be undefined by default.

File: public/js/apps/transaction/app.jsx [hunk 3]
```diff
@@ -34,55 +35,75 @@ export class TransactionApp extends Component {
...
     } else {
-      console.log('rendering purchase flow');
-      return (
-        <Transaction
-          productId={state.productId}
-          userDefinedAmount={state.userDefinedAmount}
-        />
-      );
+
+      var SignIn = this.props.SignIn;
```
Comment (muffinresearch) [inline public/js/apps/transaction/app.jsx]: We could probably move these into the de-structuring assignment above.

**Comment by muffinresearch** [comment]
This looks fine to me. iirc this was as specced for the transaction flow in the past.

r+wc

File: public/js/actions/app.js [hunk 4]
```diff
@@ -1,9 +1,10 @@
 import * as actionTypes from 'constants/action-types';
 
 
-export function error(debugMessage) {
+export function error(debugMessage, {userMessage} = {}) {
   return {
     type: actionTypes.APP_ERROR,
-    error: {debugMessage: debugMessage},
+    error: {debugMessage: debugMessage,
+            userMessage: userMessage},
```
Comment (muffinresearch) [inline public/js/actions/app.js]: This might look nicer like so: 

```
error: {
  debugMessage: debugMessage,
  userMessage: userMessage,
},
```

File: public/js/apps/transaction/app.jsx (hunk 1 above)
Comment (kumar303) [inline public/js/apps/transaction/app.jsx]: oh yeah, heh

File: tests/reducers/test.app-reducer.js (hunk 2 above)
Comment (kumar303) [inline tests/reducers/test.app-reducer.js]: I was scratching my head on this but `assert.deepEqual` was failing without it. Maybe it looks at object keys first but it's curious how the key is available when its value is undefined.

Comment (muffinresearch) [inline tests/reducers/test.app-reducer.js]: Oh strange. Maybe add a comment so it doesn't get factored out?

Comment (kumar303) [inline tests/reducers/test.app-reducer.js]: the tests will fail :)

Comment (muffinresearch) [inline tests/reducers/test.app-reducer.js]: mal-uh-whut
