### PR TITLE
Make ok button work under webpack (fixes mozilla/payments-client#36)

### LINKED ISSUE #36: Flag bug in react-maskedinput to upstream
Currently there's nothing built into the react-maskedinput to dynamically change patterns.

### PR DESCRIPTION
**Pull request by muffinresearch**

### CODE REVIEW

File: public/js/views/transaction/complete-payment.jsx [hunk 1]
```diff
@@ -27,14 +27,28 @@ export default class CompletePayment extends Component {
   handleClick = (e) => {
     e.preventDefault();
     var win = this.props.win;
-    if (win.parent !== window) {
+    var _parent = win.parent;
+
+    // TODO: wrap this so dead code elimination removes it
+    // it's just to make the OK button work when served by
```
Comment (kumar303) [inline public/js/views/transaction/complete-payment.jsx]: nit: this line should be the start of a new sentence.

File: public/js/views/transaction/complete-payment.jsx [hunk 2]
```diff
@@ -27,14 +27,28 @@ export default class CompletePayment extends Component {
...
+    // webpack-dev-server.
+    try {
+      if (_parent.location.hostname === 'pay.webpack') {
+        _parent = _parent.parent;
```
Comment (kumar303) [inline public/js/views/transaction/complete-payment.jsx]: it might be nice to add a log message here saying that `_parent` was pushed up a level

**Comment by kumar303** [comment]
r+wc
